### ISSUE TITLE
Dual sim support

### ISSUE THREAD

**Issue by slowcyclist** [slowcyclist/auto-enter-pin#1]
as per [the first comment to my answer in TJC](https://together.jolla.com/question/189508/auto-unlock-sim-card-dont-ask-for-the-sim-pin/?answer=194625#post-id-194625), it would be nice to fully support dual sims. Unfortunately, this is not something that I can test. I need help!

As it is presently, the code assumes a single sim is present. It is almost certain that it would fail if two sims are present.

Could someone provide me with the ouput (properly anonymized!) of `list-modem` on a dual-sim phone with two sims present?

**Comment by revad** [comment]
Jolla C
SIM1 is 3 - does not ask for PIN
SIM2 is giffgaff - does ask for PIN (to ensure that SIM1 connects first so that Bluetooth works in car)

[root@Sailfish nemo]# /usr/lib/ofono/test/list-modems
[ /ril_1 ]
    Emergency = 0
    Revision = 4-00034-M8909EAAAANVZM-1.38108.1
    Lockdown = 0
    Powered = 1
    Online = 1
    Serial = 356396070xxxxxx
    Type = hardware
    SoftwareVersionNumber = 00
    Features = cbs rat ussd net gprs sms stk sim 
    Interfaces = org.ofono.CellBroadcast org.ofono.RadioSettings org.ofono.NetworkMonitor org.ofono.CallSettings org.ofono.SupplementaryServices org.ofono.NetworkRegistration org.ofono.CallVolume org.ofono.CallBarring org.ofono.CallForwarding org.ofono.Phonebook org.ofono.ConnectionManager org.ofono.SmartMessaging org.ofono.PushNotification org.ofono.MessageManager org.ofono.NetworkTime org.ofono.MessageWaiting org.ofono.SimToolkit org.ofono.AllowedAccessPoints org.ofono.VoiceCallManager org.ofono.SimManager org.ofono.OemRaw org.nemomobile.ofono.CellInfo org.nemomobile.ofono.SimInfo 
    [ org.ofono.CellBroadcast ]
        Powered = 1
        Topics = 
    [ org.ofono.RadioSettings ]
        TechnologyPreference = umts
        AvailableTechnologies = gsm umts lte 
    [ org.ofono.NetworkMonitor ]
    [ org.ofono.CallSettings ]
        ConnectedLinePresentation = unknown
        VoiceCallWaiting = disabled
        ConnectedLineRestriction = unknown
        CalledLinePresentation = disabled
        HideCallerId = default
        CallingLinePresentation = enabled
        CallingNamePresentation = unknown
        CallingLineRestriction = off
    [ org.ofono.SupplementaryServices ]
        State = idle
    [ org.ofono.NetworkRegistration ]
        Technology = gsm
        LocationAreaCode = 21579
        Status = registered
        Name = giffgaff
        Mode = auto
        MobileCountryCode = 234
        MobileNetworkCode = 10
        CellId = 36237
        Strength = 51
    [ org.ofono.CallVolume ]
        SpeakerVolume = 0
        MicrophoneVolume = 0
        Muted = 1
    [ org.ofono.CallBarring ]
        VoiceIncoming = disabled
        VoiceOutgoing = disabled
    [ org.ofono.CallForwarding ]
        VoiceBusy = +447802xxxxxx
        ForwardingFlagOnSim = 0
        VoiceUnconditional = 
        VoiceNoReplyTimeout = 20
        VoiceNoReply = +44780xxxxxx
        VoiceNotReachable = +447802xxxxxx
    [ org.ofono.Phonebook ]
    [ org.ofono.ConnectionManager ]
        Powered = 1
        Bearer = none
        Attached = 0
        RoamingAllowed = 0
    [ org.ofono.SmartMessaging ]
    [ org.ofono.PushNotification ]
    [ org.ofono.MessageManager ]
        UseDeliveryReports = 0
        Bearer = cs-preferred
        Alphabet = default
        ServiceCenterAddress = +447802xxxxxx
    [ org.ofono.NetworkTime ]
    [ org.ofono.MessageWaiting ]
        VoicemailWaiting = 0
        VoicemailMailboxNumber = 
        VoicemailMessageCount = 0
    [ org.ofono.SimToolkit ]
        MainMenu = 
        MainMenuTitle = 
        IdleModeText = 
        IdleModeIcon = 
        MainMenuIcon = 
    [ org.ofono.AllowedAccessPoints ]
    [ org.ofono.VoiceCallManager ]
        EmergencyNumbers = #911 *911 999 112 911 
    [ org.ofono.SimManager ]
        CardIdentifier = 8944110065378xxxxxx
        SubscriberNumbers = 
        FixedDialing = 0
        LockedPins = pin 
        SubscriberIdentity = 234108226xxxxxx
        Present = 1
        BarredDialing = 0
        MobileCountryCode = 234
        PreferredLanguages = en 
        PinRequired = none
        MobileNetworkCode = 10
        Retries = [puk = 10] [pin2 = 3] [pin = 3] [puk2 = 10] 
        ServiceProviderName = giffgaff
    [ org.ofono.OemRaw ]
    [ org.nemomobile.ofono.CellInfo ]
    [ org.nemomobile.ofono.SimInfo ]

[ /ril_0 ]
    Emergency = 0
    Revision = 4-00034-M8909EAAAANVZM-1.38108.1
    Lockdown = 0
    Powered = 1
    Online = 1
    Serial = 356396070xxxxxx
    Type = hardware
    SoftwareVersionNumber = 00
    Features = cbs rat ussd net gprs sms stk sim 
    Interfaces = org.ofono.CellBroadcast org.ofono.RadioSettings org.ofono.NetworkMonitor org.ofono.CallSettings org.ofono.SupplementaryServices org.ofono.NetworkRegistration org.ofono.CallVolume org.ofono.CallBarring org.ofono.CallForwarding org.ofono.Phonebook org.ofono.ConnectionManager org.ofono.SmartMessaging org.ofono.PushNotification org.ofono.MessageManager org.ofono.NetworkTime org.ofono.SmsHistory org.ofono.MessageWaiting org.ofono.SimToolkit org.ofono.AllowedAccessPoints org.ofono.VoiceCallManager org.ofono.SimManager org.ofono.OemRaw org.nemomobile.ofono.CellInfo org.nemomobile.ofono.SimInfo 
    [ org.ofono.CellBroadcast ]
        Powered = 1
        Topics = 0,2,4,9,32,57,585
    [ org.ofono.RadioSettings ]
        TechnologyPreference = umts
        AvailableTechnologies = gsm umts lte 
    [ org.ofono.NetworkMonitor ]
    [ org.ofono.CallSettings ]
        ConnectedLinePresentation = unknown
        VoiceCallWaiting = enabled
        ConnectedLineRestriction = unknown
        CalledLinePresentation = disabled
        HideCallerId = default
        CallingLinePresentation = disabled
        CallingNamePresentation = unknown
        CallingLineRestriction = off
    [ org.ofono.SupplementaryServices ]
        State = idle
    [ org.ofono.NetworkRegistration ]
        Technology = umts
        LocationAreaCode = 1234
        Status = registered
        Name = 3
        Mode = auto
        MobileCountryCode = 234
        MobileNetworkCode = 20
        CellId = 10689386
        Strength = 41
    [ org.ofono.CallVolume ]
        SpeakerVolume = 0
        MicrophoneVolume = 0
        Muted = 1
    [ org.ofono.CallBarring ]
        VoiceIncoming = disabled
        VoiceOutgoing = disabled
    [ org.ofono.CallForwarding ]
        VoiceBusy = 
        ForwardingFlagOnSim = 0
        VoiceUnconditional = 
        VoiceNoReplyTimeout = 20
        VoiceNoReply = 
        VoiceNotReachable = 
    [ org.ofono.Phonebook ]
    [ org.ofono.ConnectionManager ]
        Powered = 1
        Bearer = none
        Attached = 1
        Suspended = 0
        RoamingAllowed = 1
    [ org.ofono.SmartMessaging ]
    [ org.ofono.PushNotification ]
    [ org.ofono.MessageManager ]
        UseDeliveryReports = 1
        Bearer = cs-preferred
        Alphabet = default
        ServiceCenterAddress = +447782xxxxxx
    [ org.ofono.NetworkTime ]
    [ org.ofono.SmsHistory ]
    [ org.ofono.MessageWaiting ]
        VoicemailWaiting = 0
        VoicemailMailboxNumber = +447782xxxxxx
        VoicemailMessageCount = 0
    [ org.ofono.SimToolkit ]
        MainMenu = 
        MainMenuTitle = 
        IdleModeText = 
        IdleModeIcon = 
        MainMenuIcon = 
    [ org.ofono.AllowedAccessPoints ]
    [ org.ofono.VoiceCallManager ]
        EmergencyNumbers = #911 *911 999 112 911 
    [ org.ofono.SimManager ]
        CardIdentifier = 8944200010541xxxxxx
        SubscriberNumbers = +447456xxxxxx 
        FixedDialing = 0
        LockedPins = 
        SubscriberIdentity = 234200202xxxxxx
        Present = 1
        BarredDialing = 0
        MobileCountryCode = 234
        PreferredLanguages = en 
        PinRequired = none
        MobileNetworkCode = 20
        Retries = [puk = 10] [pin2 = 3] [pin = 3] [puk2 = 10] 
        ServiceNumbers = [3 PAYG Topup/Balance] = '+447782333444' [3 Make a Payment] = '+447782333400' [3 Directory Enquiry] = '118333' [3 Voicemail] = '+447782xxxxxx' 
    [ org.ofono.OemRaw ]
    [ org.nemomobile.ofono.CellInfo ]
    [ org.nemomobile.ofono.SimInfo ]

[root@Sailfish nemo]# 

revad=DaveRo

**Comment by slowcyclist** [comment]
Thanks a lot for your input! I've commited the changes for dual sim support. It still works for my single sim (!) Would you be kind enough to test it for the real dual sim case?
Let me know if it does not work as expected of if you have any trouble configuring.

Any suggestions (within the reasonable..) are welcome too.

**Comment by revad** [comment]
I set it up with both simcardidentifiers, SIM1 pin blank and SIM2 pin set.
Used auto install.
Reboot and both SIMs worked.

So on the basis of that single test it looks OK to me : )

To run list-modems yesterday I had to find out that it's part of ofono, and I then install ofono-tests:
```
devel-su
pkcon install ofono-tests
/usr/lib/ofono/test/list-modems
```
You might note that in your instructions.

Now, how can I ensure that SIM2 connects after SIM1 so my car bluetooth works. It's the only reason I have PIN active on SIM2 (both cards are PAYG with small balances). An optional n seconds sleep before entering a pin? I can edit auto-enter-pin.py if you don't want to make it a permanent feature.

**Comment by slowcyclist** [comment]
Thanks for the feedback and glad to see it works.
list-modems is provided directly in the this repo (and yes, it is copied from ofono). I'll clarify the instructions.
Regarding controlling in which order the sims get unlocked, I can probably add that option in the settings and make it available for for everyone... I'll close this issue when it's done.

**Comment by revad** [comment]
In my case, only SIM2 requiring a PIN, SIM1 now seems to reliably connect first. The delay caused by the script is enough. But in the case of two PINs I would have thought that an optional? feature  to delay one of them might be useful. Would anybody want SIM2 connected first? I don't know.

The thread about Bluetooth and dual SIMs is here:
https://together.jolla.com/question/168601/dual-sim-choose-sim-for-bluetooth-hfp-connection/

**Comment by slowcyclist** [comment]
Ok, with the new [commit](https://github.com/slowcyclist/auto-enter-pin/commit/c9b574b2462efafe51f20ac9af2d648313f96f2c)  it is now possible to specify in the settings which sim should come up first (whether it's pin is locked or not), and to control the delay before unlocking the other sim's pin (which obviously requires that pin to be locked). So it should suit your needs. Let me know if it works.

It took a little bit more thinking than I had anticipated...

**Comment by revad** [comment]
I added a pin on SIM1. It works OK.
I suspect that 5 seconds priority delay is enough

I've now removed the pin on SIM1 and commented out the SIM1 and priority stuff and that works too. (If the phone breaks and I extract the SIM I won't need to google for the default 3UK PIN.)

Thanks for this script. 
I suggest you add a comment to the workround on the TJC Bluetooth/HFP thread above,

**Comment by slowcyclist** [comment]
Thanks for the suggestions, your input and the positive feedback!
